modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Thutmose/ThutEssentials/issues"

[[mods]]
    modId="thutessentials"
    version="${file.jarVersion}"
    displayName="Thut Essentials"
    authors="Thutmose"
    description='''
    Essentials mod for Forge
    '''
    
[[dependencies.thutessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="version_mc"
    ordering="NONE"
    side="BOTH"